// Search | Search for files and directories easier
// Copyright (C) 2026  Ametrine Foundation

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

#include "include/utilities.h"
#include <cstdio>
#include <cstring>
#include <exception>
#include <filesystem>
#include <fstream>
#include <string>

namespace fs = std::filesystem;

int configGenerate() {
    std::filesystem::path config_filepath = CONFIG_FILE_PATH;
    std::filesystem::path parent_dir = config_filepath.parent_path();

    try {
        // Create the parent directories for the config file if they don't exist
        if (!parent_dir.empty()) {
            fs::create_directories(parent_dir);
        }

        // Open the config file for writing
        std::ofstream file(config_filepath);

        if (file.is_open()) {
            // Write default content to the config file
            file << "-- Search Configuration File --\n";
            file << "-- This file is automatically generated. Do not edit unless you know what you are doing.\n\n";
            file << "local use_config = true\n";  // Default setting for configManager
            file << "local explore_all = false\n"; // Default setting for readConfigFile
            // The file will be automatically closed when 'file' goes out of scope

            return 0; // Success
        } else {
            // Log an error if the file could not be opened for writing
            char buffer[MAX_BUFFER_SIZE];
            snprintf(buffer, sizeof(buffer), "Error: Could not open config file for writing: %s\n", config_filepath.c_str());
            elogs(buffer);
            return 1; // Failure
        }
    } catch (const fs::filesystem_error& e) {
        // Catch specific filesystem errors (e.g., permissions issues, invalid path)
        char buffer[MAX_BUFFER_SIZE];
        snprintf(buffer, sizeof(buffer), "Filesystem error during config generation for '%s': %s\n", config_filepath.c_str(), e.what());
        elogs(buffer);
        return 1; // Failure
    } catch (const std::exception& e) {
        // Catch any other standard exceptions during the process
        char buffer[MAX_BUFFER_SIZE];
        snprintf(buffer, sizeof(buffer), "Unexpected error during config generation for '%s': %s\n", config_filepath.c_str(), e.what());
        elogs(buffer);
        return 1; // Failure
    }
}


int configManager() {

    std::string filename = CONFIG_FILE_PATH;

    try {
        std::ifstream file(filename);
        if (!file.is_open()) {
            throw std::runtime_error("Failed to open config file");
        }

        std::string line;
        while (std::getline(file, line)) {
            if (line.find("--") == 0) {
                continue;
            }

            if (line.find("local") == 0) {
                std::string key = line.substr(6);

                char buffer[MAX_BUFFER_SIZE];

                if (key.find(USE_CONFIG) == 0) {
                    std::string value = key.substr(USE_CONFIG.size());
                    size_t pos_space = 0;

                    while ((pos_space = value.find(" ", pos_space)) != std::string::npos) {
                        value.replace(pos_space, 1, "");
                    }

                    size_t pos_equals = 0;

                    while ((pos_equals = value.find("=", pos_equals)) != std::string::npos) {
                        value.replace(pos_equals, 1, "");
                    }

                    snprintf(buffer, sizeof(buffer), "%s | %s", USE_CONFIG.c_str(), value.c_str());
                    logs("configManager", buffer);

                    if (strcmp(value.c_str(), "false") == 0) {
                        return 1;
                    }
                }
            }
        }
    } catch (std::exception& e) {
        char buffer[MAX_BUFFER_SIZE];

        snprintf(buffer, sizeof(buffer), "Error reading config file: %s\n", filename.c_str());
        elogs(buffer);
    }
    return 0;
}


int readConfigFile() {

    std::string filename = CONFIG_FILE_PATH;

    try {
        std::ifstream file(filename);
        if (!file.is_open()) {
            throw std::runtime_error("Failed to open config file");
        }

        std::string line;
        while (std::getline(file, line)) {

            if (!use_config_file) {
                return -1;
            }

            if (line.find("--") == 0) {
                continue;
            }

            if (line.find("local") == 0) {
                std::string key = line.substr(6);

                char buffer[MAX_BUFFER_SIZE];

                if (key.find(EXPLORE_ALL) == 0) {
                    std::string value = key.substr(EXPLORE_ALL.size());
                    size_t pos_space = 0;

                    while ((pos_space = value.find(" ", pos_space)) != std::string::npos) {
                        value.replace(pos_space, 1, "");
                    }

                    size_t pos_equals = 0;

                    while ((pos_equals = value.find("=", pos_equals)) != std::string::npos) {
                        value.replace(pos_equals, 1, "");
                    }

                    snprintf(buffer, sizeof(buffer), "%s | %s\n", EXPLORE_ALL.c_str(), value.c_str());
                    logs("ConfigManager", buffer);

                    bool should;

                    if (strcmp(value.c_str(), "false") == 0) {
                        Utilities::explore_all = false;
                    } else {
                        Utilities::explore_all = true;
                    }
                }
            }
        }
    } catch (std::exception& e) {
        char buffer[MAX_BUFFER_SIZE];

        snprintf(buffer, sizeof(buffer), "Error reading config file: %s\n", filename.c_str());
        elogs(buffer);
    }
    return 0;
}
