-- Search Configuration File --
-- This file is automatically generated. Do not edit unless you know what you are doing.

local use_config = true
local explore_all = false
local ignore_gitignore = false
local ignore_hidden = false

-- Colorscheme --
-- Colorscheme for the search results. --
-- Only ANSI color codes are supported at the moment. --

local dir = "red"
local files = "green"
